# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logical_plan/v1/enums.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'logical_plan/v1/enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blogical_plan/v1/enums.proto\x12\x0flogical_plan.v1*\x82\x01\n\x08Operator\x12\x06\n\x02\x45Q\x10\x00\x12\n\n\x06NOT_EQ\x10\x01\x12\x06\n\x02LT\x10\x02\x12\x08\n\x04LTEQ\x10\x03\x12\x06\n\x02GT\x10\x04\x12\x08\n\x04GTEQ\x10\x05\x12\x08\n\x04PLUS\x10\x06\x12\t\n\x05MINUS\x10\x07\x12\x0c\n\x08MULTIPLY\x10\x08\x12\n\n\x06\x44IVIDE\x10\t\x12\x07\n\x03\x41ND\x10\n\x12\x06\n\x02OR\x10\x0b*9\n\x13\x43hunkLengthFunction\x12\r\n\tCHARACTER\x10\x00\x12\x08\n\x04WORD\x10\x01\x12\t\n\x05TOKEN\x10\x02*7\n\x11\x43hunkCharacterSet\x12\n\n\x06\x43USTOM\x10\x00\x12\t\n\x05\x41SCII\x10\x01\x12\x0b\n\x07UNICODE\x10\x02*?\n\x08JoinType\x12\t\n\x05INNER\x10\x00\x12\x08\n\x04\x46ULL\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\x12\t\n\x05\x43ROSS\x10\x04*u\n\x15\x46uzzySimilarityMethod\x12\t\n\x05INDEL\x10\x00\x12\x0f\n\x0bLEVENSHTEIN\x10\x01\x12\x17\n\x13\x44\x41MERAU_LEVENSHTEIN\x10\x02\x12\x10\n\x0cJARO_WINKLER\x10\x03\x12\x08\n\x04JARO\x10\x04\x12\x0b\n\x07HAMMING\x10\x05*1\n\x0e\x44ocContentType\x12\x0c\n\x08MARKDOWN\x10\x00\x12\x08\n\x04JSON\x10\x01\x12\x07\n\x03PDF\x10\x02\x42z\n\x13\x63om.logical_plan.v1B\nEnumsProtoP\x01\xa2\x02\x03LXX\xaa\x02\x0eLogicalPlan.V1\xca\x02\x0eLogicalPlan\\V1\xe2\x02\x1aLogicalPlan\\V1\\GPBMetadata\xea\x02\x0fLogicalPlan::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logical_plan.v1.enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.logical_plan.v1B\nEnumsProtoP\001\242\002\003LXX\252\002\016LogicalPlan.V1\312\002\016LogicalPlan\\V1\342\002\032LogicalPlan\\V1\\GPBMetadata\352\002\017LogicalPlan::V1'
  _globals['_OPERATOR']._serialized_start=49
  _globals['_OPERATOR']._serialized_end=179
  _globals['_CHUNKLENGTHFUNCTION']._serialized_start=181
  _globals['_CHUNKLENGTHFUNCTION']._serialized_end=238
  _globals['_CHUNKCHARACTERSET']._serialized_start=240
  _globals['_CHUNKCHARACTERSET']._serialized_end=295
  _globals['_JOINTYPE']._serialized_start=297
  _globals['_JOINTYPE']._serialized_end=360
  _globals['_FUZZYSIMILARITYMETHOD']._serialized_start=362
  _globals['_FUZZYSIMILARITYMETHOD']._serialized_end=479
  _globals['_DOCCONTENTTYPE']._serialized_start=481
  _globals['_DOCCONTENTTYPE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
