# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logical_plan/v1/tools.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'logical_plan/v1/tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fenic._gen.protos.logical_plan.v1 import datatypes_pb2 as logical__plan_dot_v1_dot_datatypes__pb2
from fenic._gen.protos.logical_plan.v1 import complex_types_pb2 as logical__plan_dot_v1_dot_complex__types__pb2
from fenic._gen.protos.logical_plan.v1 import plans_pb2 as logical__plan_dot_v1_dot_plans__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blogical_plan/v1/tools.proto\x12\x0flogical_plan.v1\x1a\x1flogical_plan/v1/datatypes.proto\x1a#logical_plan/v1/complex_types.proto\x1a\x1blogical_plan/v1/plans.proto\"\xd9\x02\n\rToolParameter\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x36\n\tdata_type\x18\x03 \x01(\x0b\x32\x19.logical_plan.v1.DataTypeR\x08\x64\x61taType\x12\x1a\n\x08required\x18\x04 \x01(\x08R\x08required\x12\x1f\n\x0bhas_default\x18\x05 \x01(\x08R\nhasDefault\x12\x46\n\rdefault_value\x18\x06 \x01(\x0b\x32\x1c.logical_plan.v1.ScalarValueH\x00R\x0c\x64\x65\x66\x61ultValue\x88\x01\x01\x12\x43\n\x0e\x61llowed_values\x18\x07 \x03(\x0b\x32\x1c.logical_plan.v1.ScalarValueR\rallowedValuesB\x10\n\x0e_default_value\"\xee\x01\n\x0eToolDefinition\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x36\n\x06params\x18\x03 \x03(\x0b\x32\x1e.logical_plan.v1.ToolParameterR\x06params\x12K\n\x12parameterized_view\x18\x04 \x01(\x0b\x32\x1c.logical_plan.v1.LogicalPlanR\x11parameterizedView\x12!\n\x0cresult_limit\x18\x05 \x01(\x05R\x0bresultLimitBz\n\x13\x63om.logical_plan.v1B\nToolsProtoP\x01\xa2\x02\x03LXX\xaa\x02\x0eLogicalPlan.V1\xca\x02\x0eLogicalPlan\\V1\xe2\x02\x1aLogicalPlan\\V1\\GPBMetadata\xea\x02\x0fLogicalPlan::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logical_plan.v1.tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.logical_plan.v1B\nToolsProtoP\001\242\002\003LXX\252\002\016LogicalPlan.V1\312\002\016LogicalPlan\\V1\342\002\032LogicalPlan\\V1\\GPBMetadata\352\002\017LogicalPlan::V1'
  _globals['_TOOLPARAMETER']._serialized_start=148
  _globals['_TOOLPARAMETER']._serialized_end=493
  _globals['_TOOLDEFINITION']._serialized_start=496
  _globals['_TOOLDEFINITION']._serialized_end=734
# @@protoc_insertion_point(module_scope)
